name: app
description: Google Developer Student Clubs Solution Challenge 23 Projects.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
     - family: NotoSans
       fonts:
         - asset: assets/fonts/NotoSansKR-Thin.otf
           weight: 100
         - asset: assets/fonts/NotoSansKR-Light.otf
           weight: 300
         - asset: assets/fonts/NotoSansKR-Regular.otf
           weight: 400
         - asset: assets/fonts/NotoSansKR-Medium.otf
           weight: 500
         - asset: assets/fonts/NotoSansKR-Bold.otf
           weight: 700
         - asset: assets/fonts/NotoSansKR-Black.otf
           weight: 900
