name: zikiza
description: Google Solution Challenge 23 Project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  dynamic_color: ^1.6.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  freezed: ^2.3.2
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.4
  html: ^0.15.1
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
     - family: NotoSans
       fonts:
         - asset: assets/fonts/NotoSansKR-Thin.otf
           weight: 100
         - asset: assets/fonts/NotoSansKR-Light.otf
           weight: 300
         - asset: assets/fonts/NotoSansKR-Regular.otf
           weight: 400
         - asset: assets/fonts/NotoSansKR-Medium.otf
           weight: 500
         - asset: assets/fonts/NotoSansKR-Bold.otf
           weight: 700
         - asset: assets/fonts/NotoSansKR-Black.otf
           weight: 900
